language: python

python:
  - "2.7"

env:
  - VERSION="7.0" LINT_CHECK="0" TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="ovl"
  - VERSION="7.0" LINT_CHECK="1" TESTS="0" ODOO_REPO="odoo/odoo" INCLUDE="ovl"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - ${TRAVIS_BUILD_DIR}/travis/travis_install_ve_nightly ${VERSION}
  - git clone --single-branch --depth=1 https://github.com/Vauxoo/addons-vauxoo.git -b ${VERSION} ${HOME}/addons-vauxoo

script:
  - travis_wait travis_run_tests

after_success:
  - travis_after_tests_success
